# Generated by Django 4.2.11 on 2024-07-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user has verified their email.",
            ),
        ),
    ]
